server:
  port: 8100

eureka:
  client:
    service-url:
      default-zone:
        http://localhost:8762/eureka/

spring:
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/leo-k-ljf/myConfig/
          search-paths:
            - respo
          username:
          password:
